### ISSUE TITLE
Client creates table and SETs

### ISSUE THREAD

**Issue by mtrencseni** [scalien/scaliendb#121]
But table has not yet "arrived" on the shard server.

---

Egy kicsit hosszabb program:

import com.scalien.scaliendb.Client;
import com.scalien.scaliendb.Database;
import com.scalien.scaliendb.Quorum;
import com.scalien.scaliendb.SDBPException;
import com.scalien.scaliendb.Table;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
- Set up database
  *
- @author sp
  */

public class Proba2 {

   // sequences

   private static final Map<String, Long> SEQUENCES;
   static {
       SEQUENCES = new HashMap<String, Long> ();
       SEQUENCES.put ("assertion", 1L);
       SEQUENCES.put ("entity", 10000L);
   }

   /**
    \* Main method
    *
    \* @param args command line arguments
    */

   public static void main (String [] args) throws SDBPException {

```
   // check number command line arguments

   if (args.length != 2) {
       System.out.println ("Usage: [program] <controller> <quorum>");
       return;
   }

   // delete database if exists

   Client client = new Client (Arrays.copyOf (args, 1));
   for (Database database: client.getDatabases ())
       if (database.getName ().equals ("naxos")) {
           database.deleteDatabase ();
           break;
       }

   // capture quorum and database objects

   Database database = client.createDatabase ("naxos");
   long quorumId = Long.parseLong (args [1]);
   Quorum quorum = client.getQuorum (quorumId);

   // set up sequence table

   Table table = database.createTable (quorum, "sequence");
   for (Map.Entry<String, Long> sequence: SEQUENCES.entrySet ())
       table.setLong (sequence.getKey (), sequence.getValue ());
```

   }
}

Ezzel az a gond, hogy időnként ezt az exceptiont dobja, -402-es kóddal
(a table.setLong-os sorra):

Exception in thread "main" com.scalien.scaliendb.SDBPException
       at com.scalien.scaliendb.Client.checkStatus(Client.java:1204)
       at com.scalien.scaliendb.Client.checkStatus(Client.java:1186)
       at com.scalien.scaliendb.Client.set(Client.java:570)
       at com.scalien.scaliendb.Table.setLong(Table.java:153)
       at Proba2.main(Proba2.java:62)

máskor viszont tökéletesen lefut.

**Comment by mtrencseni** [comment]
Temp. fix in

  https://github.com/scalien/scaliendb/commit/b715aa6b4b9fec0e7edce8b7d156ef556d32fcf4
