### ISSUE TITLE
Client - Controller - ShardServer serialization during schema change

### ISSUE THREAD

**Issue by mtrencseni** [scalien/scaliendb#148]
Koszi, megvan a baj:
1. a kliens elkuld egy CREATE_TABLE-t a controllernek
2. a controller letrehozza a tablat, kliensnek OK
3. a kliens a tablaba bele akar irni
4. a shard serverhez meg nem ert el az uj tabla hire, ezert BAD_SCHEMA-t dob vissza
5. kliens exception lesz

Erre regebben csinaltam egy "hack" megoldast, hogy sema muvelet utan a kliens direkt alszik 20msec-et, es ez itt meg is van, latszik a log-ban, de neha nem eleg a 20msec...

On Fri, Jul 8, 2011 at 12:08 PM, Peter Schonhofen schonhofen@gmail.com wrote:

```
^Csp@atlas:/work/naxos/target/classes$ java -cp ~/scaliendb/bin/java/scaliendb.jar:. hu.in4.naxos.maintenance.SetUpDatabe 192.168.1.200:7080 1
2011-07-08 12:07:59.600482: SDBPClient.cpp:295:GetConfigState()
2011-07-08 12:07:59.600526: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.600610: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.600656: SDBPControllerConnection.cpp:134:OnConnect()
2011-07-08 12:07:59.600671: TCPConnection.cpp:138:OnConnect()
2011-07-08 12:07:59.600689: TCPConnection.cpp:92:OnWritePending(): fd = 15
2011-07-08 12:07:59.600703: TCPWriter.cpp:79:GetNext()
2011-07-08 12:07:59.600714: TCPConnection.cpp:73:AsyncRead()
2011-07-08 12:07:59.600766: SDBPControllerConnection.cpp:47:Send(): type = A, nodeID = 0
2011-07-08 12:07:59.600841: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.600864: TCPWriter.cpp:63:Flush()
2011-07-08 12:07:59.600874: TCPConnection.cpp:92:OnWritePending(): fd = 15
2011-07-08 12:07:59.600883: TCPWriter.cpp:79:GetNext()
2011-07-08 12:07:59.600927: TCPConnection.cpp:129:OnWrite(): Written 5 bytes on 15
2011-07-08 12:07:59.600942: TCPConnection.cpp:130:OnWrite(): Written on 15: 3:A:1
2011-07-08 12:07:59.600952: TCPWriter.cpp:93:OnNextWritten()
2011-07-08 12:07:59.600969: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.681703: MessageConnection.cpp:140:OnRead(): Read buffer: 53:_:0:1:44:SDBP client protocol, server version v1.9.9

2011-07-08 12:07:59.681834: SDBPControllerConnection.cpp:105:OnMessage()
2011-07-08 12:07:59.681921: MessageConnection.cpp:224:OnRead(): time spent in OnRead(): 0
2011-07-08 12:07:59.681943: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.681967: MessageConnection.cpp:140:OnRead(): Read buffer: 976:C:1:C:Y:0:P197:N:2:21:156:156:101:1:1:4:main:1:100:0:11:145:146:147:148:149:150:151:152:153:154:155:0:N:26576:Y:100:1:20:5:naxos:11:145:146:147:148:149:150:151:152:153:154:155:11:20:145:8:sequence:F:1:145:20:146:9:assertion:F:1:146:20:147:13:index_boolean:F:1:147:20:148:10:index_text:F:1:148:20:149:12:index_number:F:1:149:20:150:10:index_date:F:1:150:20:151:15:index_reference:F:1:151:20:152:10:index_name:F:1:152:20:153:7:history:F:1:153:20:154:12:index_action:F:1:154:20:155:14:index_chaining:F:1:155:11:1:145:145:0::0::0:0:59:6:entity:1:146:146:0::0::0:0:26547:8:2011-07-08 12:07:59.681988: SDBPControllerConnection.cpp:105:OnMessage()
2011-07-08 12:07:59.682166: SDBPClient.cpp:890:SetMaster(): known master: -1, set master: 0, nodeID: 0
2011-07-08 12:07:59.682185: Node 0 is the master
2011-07-08 12:07:59.682202: SDBPClient.cpp:1402:ConfigureShardServers(): 1
2011-07-08 12:07:59.682215: SDBPClient.cpp:1406:ConfigureShardServers(): 100
2011-07-08 12:07:59.682226: SDBPClient.cpp:1409:ConfigureShardServers(): connect
2011-07-08 12:07:59.682245: MessageConnection.cpp:29:Connect()
2011-07-08 12:07:59.682273: TCPConnection.cpp:26:Connect(): endpoint_ = 192.168.1.200:7090
2011-07-08 12:07:59.682285: TCPConnection.cpp:113:Init()
2011-07-08 12:07:59.682295: TCPConnection.cpp:73:AsyncRead()
2011-07-08 12:07:59.682304: TCPConnection.cpp:82:AsyncRead(): not posting read
2011-07-08 12:07:59.682368: TCPConnection.cpp:48:Connect(): starting timeout with 2000
2011-07-08 12:07:59.682394: SDBPClient.cpp:1427:ConfigureShardServers(): 2
2011-07-08 12:07:59.682405: SDBPClient.cpp:1432:ConfigureShardServers(): quorumID: 1, primary: 100
2011-07-08 12:07:59.682418: SDBPClient.cpp:1435:ConfigureShardServers(): 100
2011-07-08 12:07:59.682441: SDBPClient.cpp:1252:SendQuorumRequests()
2011-07-08 12:07:59.682468: MessageConnection.cpp:224:OnRead(): time spent in OnRead(): 1
2011-07-08 12:07:59.682752: SDBPClient.cpp:295:GetConfigState()
2011-07-08 12:07:59.682776: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.682790: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: 0
2011-07-08 12:07:59.682812: SDBPShardConnection.cpp:207:OnConnect()
2011-07-08 12:07:59.682823: TCPConnection.cpp:138:OnConnect()
2011-07-08 12:07:59.682835: TCPConnection.cpp:92:OnWritePending(): fd = 16
2011-07-08 12:07:59.682846: TCPWriter.cpp:79:GetNext()
2011-07-08 12:07:59.682855: TCPConnection.cpp:73:AsyncRead()
2011-07-08 12:07:59.683940: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.683980: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: 0
2011-07-08 12:07:59.710846: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.710907: SDBPControllerConnection.cpp:47:Send(): type = D, nodeID = 0
2011-07-08 12:07:59.710934: SDBPClient.cpp:1252:SendQuorumRequests()
2011-07-08 12:07:59.710954: SDBPClient.cpp:1286:SendQuorumRequests(): conn nodeID 100, quorums.length = 1
2011-07-08 12:07:59.710971: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.710985: TCPWriter.cpp:63:Flush()
2011-07-08 12:07:59.710995: TCPConnection.cpp:92:OnWritePending(): fd = 15
2011-07-08 12:07:59.711004: TCPWriter.cpp:79:GetNext()
2011-07-08 12:07:59.711055: TCPConnection.cpp:129:OnWrite(): Written 8 bytes on 15
2011-07-08 12:07:59.711069: TCPConnection.cpp:130:OnWrite(): Written on 15: 6:D:2:20
2011-07-08 12:07:59.711080: TCPWriter.cpp:93:OnNextWritten()
2011-07-08 12:07:59.711094: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.720466: MessageConnection.cpp:140:OnRead(): Read buffer: 53:_:0:1:44:SDBP client protocol, server version v1.9.9

2011-07-08 12:07:59.720519: SDBPShardConnection.cpp:139:OnMessage(): SDBP version: 1, message: SDBP client protocol, server version v1.9.9

2011-07-08 12:07:59.720541: MessageConnection.cpp:224:OnRead(): time spent in OnRead(): 0
2011-07-08 12:07:59.720557: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.788950: MessageConnection.cpp:140:OnRead(): Read buffer: 135:C:1:C:Y:0:P198:N:2:21:156:156:101:1:1:4:main:1:100:0:0:0:N:26576:Y:100:0:0:0:1:100:19:192.168.1.200:10010:9091:7090:T:1:1:26576:F:0:0:03:O:2
2011-07-08 12:07:59.788997: SDBPControllerConnection.cpp:105:OnMessage()
2011-07-08 12:07:59.789106: SDBPClient.cpp:890:SetMaster(): known master: 0, set master: 0, nodeID: 0
2011-07-08 12:07:59.789125: SDBPClient.cpp:1402:ConfigureShardServers(): 1
2011-07-08 12:07:59.789136: SDBPClient.cpp:1406:ConfigureShardServers(): 100
2011-07-08 12:07:59.789150: SDBPClient.cpp:1419:ConfigureShardServers(): ssit: 192.168.1.200:10010, shardConn: 192.168.1.200:7090
2011-07-08 12:07:59.789166: SDBPClient.cpp:1427:ConfigureShardServers(): 2
2011-07-08 12:07:59.789176: SDBPClient.cpp:1432:ConfigureShardServers(): quorumID: 1, primary: 100
2011-07-08 12:07:59.789187: SDBPClient.cpp:1435:ConfigureShardServers(): 100
2011-07-08 12:07:59.789198: SDBPClient.cpp:1252:SendQuorumRequests()
2011-07-08 12:07:59.789210: SDBPClient.cpp:1286:SendQuorumRequests(): conn nodeID 100, quorums.length = 1
2011-07-08 12:07:59.789228: SDBPControllerConnection.cpp:105:OnMessage()
2011-07-08 12:07:59.789246: SDBPControllerConnection.cpp:232:ProcessCommandResponse()
2011-07-08 12:07:59.789261: SDBPResult.cpp:156:AppendRequestResponse(): O 2
2011-07-08 12:07:59.789285: MessageConnection.cpp:224:OnRead(): time spent in OnRead(): 1
2011-07-08 12:07:59.810600: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.810743: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.810768: SDBPControllerConnection.cpp:47:Send(): type = C, nodeID = 0
2011-07-08 12:07:59.810804: SDBPClient.cpp:1252:SendQuorumRequests()
2011-07-08 12:07:59.810819: SDBPClient.cpp:1286:SendQuorumRequests(): conn nodeID 100, quorums.length = 1
2011-07-08 12:07:59.810837: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.810851: TCPWriter.cpp:63:Flush()
2011-07-08 12:07:59.810861: TCPConnection.cpp:92:OnWritePending(): fd = 15
2011-07-08 12:07:59.810871: TCPWriter.cpp:79:GetNext()
2011-07-08 12:07:59.810926: TCPConnection.cpp:129:OnWrite(): Written 14 bytes on 15
2011-07-08 12:07:59.810940: TCPConnection.cpp:130:OnWrite(): Written on 15: 11:C:3:5:naxos
2011-07-08 12:07:59.810950: TCPWriter.cpp:93:OnNextWritten()
2011-07-08 12:07:59.810965: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.846747: MessageConnection.cpp:140:OnRead(): Read buffer: 148:C:1:C:Y:0:P199:N:2:22:156:156:101:1:1:4:main:1:100:0:0:0:N:26576:Y:100:1:21:5:naxos:0:0:0:1:100:19:192.168.1.200:10010:9091:7090:T:1:1:26576:F:0:0:06:n:3:21
2011-07-08 12:07:59.846795: SDBPControllerConnection.cpp:105:OnMessage()
2011-07-08 12:07:59.846854: SDBPClient.cpp:890:SetMaster(): known master: 0, set master: 0, nodeID: 0
2011-07-08 12:07:59.846870: SDBPClient.cpp:1402:ConfigureShardServers(): 1
2011-07-08 12:07:59.846881: SDBPClient.cpp:1406:ConfigureShardServers(): 100
2011-07-08 12:07:59.846894: SDBPClient.cpp:1419:ConfigureShardServers(): ssit: 192.168.1.200:10010, shardConn: 192.168.1.200:7090
2011-07-08 12:07:59.846906: SDBPClient.cpp:1427:ConfigureShardServers(): 2
2011-07-08 12:07:59.846915: SDBPClient.cpp:1432:ConfigureShardServers(): quorumID: 1, primary: 100
2011-07-08 12:07:59.846925: SDBPClient.cpp:1435:ConfigureShardServers(): 100
2011-07-08 12:07:59.846937: SDBPClient.cpp:1252:SendQuorumRequests()
2011-07-08 12:07:59.846948: SDBPClient.cpp:1286:SendQuorumRequests(): conn nodeID 100, quorums.length = 1
2011-07-08 12:07:59.846966: SDBPControllerConnection.cpp:105:OnMessage()
2011-07-08 12:07:59.846993: SDBPControllerConnection.cpp:232:ProcessCommandResponse()
2011-07-08 12:07:59.847006: SDBPResult.cpp:156:AppendRequestResponse(): n 3
2011-07-08 12:07:59.847024: MessageConnection.cpp:224:OnRead(): time spent in OnRead(): 1
2011-07-08 12:07:59.867130: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.867206: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.867225: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: 0
2011-07-08 12:07:59.868300: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.868349: SDBPControllerConnection.cpp:47:Send(): type = c, nodeID = 0
2011-07-08 12:07:59.868380: SDBPClient.cpp:1252:SendQuorumRequests()
2011-07-08 12:07:59.868394: SDBPClient.cpp:1286:SendQuorumRequests(): conn nodeID 100, quorums.length = 1
2011-07-08 12:07:59.868411: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.868425: TCPWriter.cpp:63:Flush()
2011-07-08 12:07:59.868435: TCPConnection.cpp:92:OnWritePending(): fd = 15
2011-07-08 12:07:59.868445: TCPWriter.cpp:79:GetNext()
2011-07-08 12:07:59.868507: TCPConnection.cpp:129:OnWrite(): Written 22 bytes on 15
2011-07-08 12:07:59.868522: TCPConnection.cpp:130:OnWrite(): Written on 15: 19:c:4:21:1:8:sequence
2011-07-08 12:07:59.868533: TCPWriter.cpp:93:OnNextWritten()
2011-07-08 12:07:59.868546: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.879748: MessageConnection.cpp:140:OnRead(): Read buffer: 207:C:1:C:Y:0:P200:N:2:22:157:157:101:1:1:4:main:1:100:0:1:156:0:N:26576:Y:100:1:21:5:naxos:1:156:1:21:156:8:sequence:F:1:156:1:1:156:156:0::0::0:0:0:0::1:100:19:192.168.1.200:10010:9091:7090:T:1:1:26576:F:0:0:07:n:4:156
2011-07-08 12:07:59.879795: SDBPControllerConnection.cpp:105:OnMessage()
2011-07-08 12:07:59.879860: SDBPClient.cpp:890:SetMaster(): known master: 0, set master: 0, nodeID: 0
2011-07-08 12:07:59.879876: SDBPClient.cpp:1402:ConfigureShardServers(): 1
2011-07-08 12:07:59.879887: SDBPClient.cpp:1406:ConfigureShardServers(): 100
2011-07-08 12:07:59.879900: SDBPClient.cpp:1419:ConfigureShardServers(): ssit: 192.168.1.200:10010, shardConn: 192.168.1.200:7090
2011-07-08 12:07:59.879912: SDBPClient.cpp:1427:ConfigureShardServers(): 2
2011-07-08 12:07:59.879921: SDBPClient.cpp:1432:ConfigureShardServers(): quorumID: 1, primary: 100
2011-07-08 12:07:59.879931: SDBPClient.cpp:1435:ConfigureShardServers(): 100
2011-07-08 12:07:59.879942: SDBPClient.cpp:1252:SendQuorumRequests()
2011-07-08 12:07:59.879953: SDBPClient.cpp:1286:SendQuorumRequests(): conn nodeID 100, quorums.length = 1
2011-07-08 12:07:59.879971: SDBPControllerConnection.cpp:105:OnMessage()
2011-07-08 12:07:59.879985: SDBPControllerConnection.cpp:232:ProcessCommandResponse()
2011-07-08 12:07:59.879997: SDBPResult.cpp:156:AppendRequestResponse(): n 4
2011-07-08 12:07:59.880014: MessageConnection.cpp:224:OnRead(): time spent in OnRead(): 1
2011-07-08 12:07:59.900117: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.900375: SDBPClient.cpp:295:GetConfigState()
2011-07-08 12:07:59.900397: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.900412: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: 0
2011-07-08 12:07:59.900467: SDBPClient.cpp:295:GetConfigState()
2011-07-08 12:07:59.900482: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.900493: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: 0
2011-07-08 12:07:59.902073: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.902117: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: 0
2011-07-08 12:07:59.902603: SDBPResult.cpp:40:Close()
2011-07-08 12:07:59.902652: SDBPClient.cpp:1252:SendQuorumRequests()
2011-07-08 12:07:59.902667: SDBPClient.cpp:1286:SendQuorumRequests(): conn nodeID 100, quorums.length = 1
2011-07-08 12:07:59.902683: SDBPClient.cpp:1171:SendQuorumRequest(): quorumID: 1, numRequests: 1, maxRequests: 0, nodeID: 100
2011-07-08 12:07:59.902713: SDBPClient.cpp:1223:SendQuorumRequest(): quorumID: 1, numServed: 1, nodeID: 100
2011-07-08 12:07:59.902734: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.902748: TCPWriter.cpp:63:Flush()
2011-07-08 12:07:59.902758: TCPConnection.cpp:92:OnWritePending(): fd = 16
2011-07-08 12:07:59.902768: TCPWriter.cpp:79:GetNext()
2011-07-08 12:07:59.902821: SDBPShardConnection.cpp:194:OnWrite()
2011-07-08 12:07:59.902847: TCPConnection.cpp:129:OnWrite(): Written 24 bytes on 16
2011-07-08 12:07:59.902857: TCPConnection.cpp:130:OnWrite(): Written on 16: 21:S:5:156:7:history:1:1
2011-07-08 12:07:59.902868: TCPWriter.cpp:93:OnNextWritten()
2011-07-08 12:07:59.902879: SDBPClient.cpp:1171:SendQuorumRequest(): quorumID: 1, numRequests: 0, maxRequests: 0, nodeID: 100
2011-07-08 12:07:59.902891: SDBPClient.cpp:1223:SendQuorumRequest(): quorumID: 1, numServed: 0, nodeID: 100
2011-07-08 12:07:59.902908: SDBPClient.cpp:819:EventLoop(): EventLoop main loop, wait: -1
2011-07-08 12:07:59.902921: TCPWriter.cpp:63:Flush()
2011-07-08 12:07:59.902931: TCPConnection.cpp:92:OnWritePending(): fd = 16
2011-07-08 12:07:59.902940: TCPWriter.cpp:79:GetNext()
2011-07-08 12:07:59.924143: MessageConnection.cpp:140:OnRead(): Read buffer: 3:B:5
2011-07-08 12:07:59.924194: SDBPResult.cpp:156:AppendRequestResponse(): B 5
2011-07-08 12:07:59.924217: MessageConnection.cpp:224:OnRead(): time spent in OnRead(): 0
2011-07-08 12:07:59.924254: SDBPResult.cpp:40:Close()
Exception in thread "main" com.scalien.scaliendb.SDBPException: No database or table is in use
    at com.scalien.scaliendb.Client.checkStatus(Client.java:1453)
    at com.scalien.scaliendb.Client.checkStatus(Client.java:1438)
    at com.scalien.scaliendb.Client.set(Client.java:613)
    at com.scalien.scaliendb.Client.setLong(Client.java:661)
    at com.scalien.scaliendb.Table.setLong(Table.java:197)
    at hu.in4.naxos.maintenance.SetUpDatabase.main(SetUpDatabase.java:506) 
```

**Comment by mtrencseni** [comment]
Fixed in

https://github.com/scalien/scaliendb/commit/04cb012762ae6f4a8c533b43233929d39f297d3d
